apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx-helm
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: "15.5.0"     # You can adjust the version as needed
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    service:
      type: ClusterIP
    replicaCount: 2
