apiVersion: apps/v1
kind: Deployment
metadata:
  name: aniket-app
  namespace: aniket-app
  labels:
    app: aniket-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aniket-app
  template:
    metadata:
      labels:
        app: aniket-app
    spec:
      containers:
        - name: aniket-container
          image: nginx:latest
          ports:
            - containerPort: 80
